name: build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            tmp
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Download tessdata for CI
        run: |
          mkdir -p tessdata
          curl -L https://github.com/tesseract-ocr/tessdata_fast/raw/main/eng.traineddata -o tessdata/eng.traineddata
          export TESSDATA_PREFIX=$PWD/tessdata

      - name: Compile native extension
        run: |
          export TESSDATA_PREFIX=$PWD/tessdata
          bundle exec rake compile

      - name: Run specs
        run: |
          export TESSDATA_PREFIX=$PWD/tessdata
          bundle exec rake spec
